[package]
name = "ipscanner"
version = "0.3.0"
description = "A modern IP scanner"
authors = ["you"]
edition = "2021"

[lib]
name = "ipscanner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
tokio-util = "0.7"
ipnet = "2"
winping = "0.10"
dns-lookup = "2"
uuid = { version = "1", features = ["v4", "serde"] }
parking_lot = "0.12"
futures = "0.3"
tauri-plugin-dialog = "2"
rust_xlsxwriter = "0.79"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
if-addrs = "0.13"
windows-sys = { version = "0.59", features = ["Win32_NetworkManagement_IpHelper", "Win32_Foundation"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
